app/user/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-


from flask import Blueprint
user = Blueprint('user', __name__)
from . import views

app/user/views.py
import os
import re
from PIL import Image
from app.utils.file_manage import get_file_type
from .. import db
from app.models import User
from . import user
from flask import render_template, redirect, request, url_for, current_app, abort, jsonify, session
from flask_login import login_user, logout_user, current_user, login_required
from datetime import datetime
from ..utils.utils import generate_password, clear_session_cookie


@user.route('/reg/', methods=['GET', 'POST'])
def reg():
    if request.method == 'GET':
        return render_template("user/reg.html", title=u"账号注册")
    elif request.method == 'POST':
        _form = request.form
        username = _form['username']
        email = _form['email']
        password = _form['password']
        password2 = _form['password2']

        """此处可继续完善后端验证，如过滤特殊字符等"""
        message_e, message_u, message_p = "", "", ""
        if User.query.filter_by(username=username).first():
            message_u = u'用户名已存在'
        if User.query.filter_by(email=email).first():
            message_e = u'邮箱已存在'
        if password != password2:
            message_p = u'两次输入密码不一致'

        if not re.search('^[a-zA-Z][a-zA-Z0-9]{2,12}$', username):
            message_u = u'用户名必须以字母开头,只能包含字母或数字, 且不能小于3位大于11位'
        # if not re.search('^[a-zA-Z][a-zA-Z0-9]{5,}$', password):
        #     message_p = u'密码只能包含字母与数字, 且不能小于6位'

        data = None
        if message_u or message_e or message_e:
            data = _form
        if message_u or message_p or message_e:
            return render_template("user/reg.html", form=_form,
                                   title=u'账号注册',
                                   message_u=message_u,
                                   message_p=message_p,
                                   message_e=message_e,
                                   data=data)
        else:
            reg_user = User()
            reg_user.email = email
            reg_user.password = password
            reg_user.username = username
            reg_user.avatar_url = current_app.config['DEFAULT_AVATAR']
            reg_user.api_password = generate_password()
            db.session.add(reg_user)
            db.session.commit()
            login_user(reg_user)
            reg_user.last_login = datetime.now()
            db.session.commit()
            return redirect(url_for('main.index'))


@user.route('/login/', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template("user/login.html", title=u"用户登录")
    elif request.method == 'POST':
        _form = request.form
        u = User.query.filter_by(email=_form['email']).first()

        if u is None:
            message_e = u'邮箱不存在'
            return render_template('user/login.html',
                                   title=u"用户登录",
                                   data=_form,
                                   message_e=message_e)

        next_url = request.args.get('next')
        if u and u.verify_password(_form['password']):
            login_user(u)
            u.last_login = datetime.now()
            db.session.commit()
            return redirect(next_url or url_for('main.index'))
        else:
            message_p = u"密码错误"
            return render_template('user/login.html',
                                   title=u"用户登录",
                                   data=_form,
                                   message_p=message_p)


@user.route('/logout/')
@login_required
def logout():
    logout_user()
    clear_session_cookie(session)
    return redirect(url_for('user.login'))


@user.route('/setting/information', methods=['GET', 'POST'])
@login_required
def setting_information():
    if request.method == 'GET':
        return render_template('user/setting_information.html', title=u'个人设置')
    elif request.method == 'POST':
        _form = request.form
        cur_user = User.query.filter_by(email=current_user.email).first()
        cur_user.phone = _form['phone']
        cur_user.real_name = _form['real_name']
        cur_user.address = _form['address']
        db.session.commit()
        return render_template('user/setting_information.html',
                               title=u'个人设置',
                               status='success')


@user.route('/setting/password', methods=['GET', 'POST'])
@login_required
def setting_password():
    if request.method == 'GET':
        return render_template('user/setting_password.html', title=u'个人设置')
    elif request.method == 'POST':
        _form = request.form
        cur_user = User.query.filter_by(email=current_user.email).first()
        if cur_user.verify_password(_form['origin_password']):
            if _form['new_password'] == _form['new_password2']:
                cur_user.password = _form['new_password']
                db.session.commit()
                return render_template('user/setting_password.html', title=u'个人设置', status='success')
            else:
                fail_message = u'两次输入新密码不一致，请重新输入'
        else:
            fail_message = u'初始密码错误，请重新输入'

        return render_template('user/setting_password.html',
                               title=u'个人设置',
                               fail_message=fail_message)


@user.route('/setting/avatar', methods=['GET', 'POST'])
@login_required
def setting_avatar():
    if request.method == 'GET':
        return render_template('user/setting_avatar.html', title=u'个人设置')
    elif request.method == 'POST':
        _file = request.files['file']
        avatar_folder = current_app.config['AVATAR_FOLDER']
        file_type = get_file_type(_file.mimetype)
        if _file and '.' in _file.filename and file_type == "img":
            im = Image.open(_file)
            im.thumbnail((128, 128), Image.ANTIALIAS)
            image_path = os.path.join(avatar_folder, "%d.png" % current_user.id)
            im.save(image_path, 'PNG')
            unique_mark = os.stat(image_path).st_mtime
            current_user.avatar_url = '/static/upload/avatar/' + '%d.png?t=%s' % (current_user.id, unique_mark)

            db.session.commit()
            message_success = u'更新图片成功'
            return render_template('user/setting_avatar.html', message_success=message_success)
        else:
            message_fail = u"无效的文件类型"
            return render_template('user/setting_avatar.html', message_fail=message_fail)

app/templates/user/login.html
{% extends 'user/login_base.html' %}

{% block content %}
<div class="content-wrapper">
    <div class="container">
        <div class="login-box" style="width: 450px;">
            <div class="login-logo">
                <a href="#">登录 <b>flask模板</b></a>
            </div>
            <div class="login-box-body">
                <p class="login-box-msg"></p>
                <form action="{{ url_for('user.login') }}" method="post" data-parsley-validate="">
                  <div class="form-group has-feedback">
                    <input name="email" type="email" class="form-control" placeholder="电子邮箱"
                           data-parsley-required-message="请输入您的登录邮箱" data-parsley-type="email"
                           data-parsley-maxlength="64" {% if data %}value="{{ data.email }}"{% endif %} required>
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                    {% if message_e %}
                        <p class="help-text">{{ message_e }}</p>
                    {% endif %}
                  </div>
                  <div class="form-group has-feedback">
                    <input name="password" type="password" class="form-control" placeholder="登录密码"
                           {% if data %}value="{{ data.password }}"{% endif %} data-parsley-type="alphanum"
                           data-parsley-required-message="请输入您的登录密码" data-parsley-length="[6,32]" required>
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    {% if message_p %}
                        <p class="help-text">{{ message_p }}</p>
                    {% endif %}
                  </div>
                  <div class="row">
                      <div class="col-xs-8" style="padding-top: 7px">
                          <a href="#">忘记密码</a> | 没有账户？<a href="{{ url_for('user.reg') }}">立即注册</a>
                      </div>
                      <div class="col-xs-4">
                        <button type="submit" class="btn btn-success btn-block btn-flat">登录</button>
                      </div>
                  </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/user/login_base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% if title %}{{ title }}{% endif %}</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/ionicons.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/AdminLTE.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/_all-skins.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
</head>

<body class="hold-transition skin-blue layout-top-nav">
<div class="wrapper">

  <header class="main-header">
    <nav class="navbar navbar-static-top" role="navigation">
        <div class="container">
            <a href="/" class="navbar-brand" style="padding: 0">
                <img src="{{ url_for('static',filename='resource/img/logo.png') }}"
                     style="height: 50px; margin: 0"></a>
            <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
              <ul class="nav navbar-nav">
                <li><a href="{{ url_for('user.login') }}">用户登录</a></li>
                <li><a href="{{ url_for('user.reg') }}">账号注册</a></li>
                <li><a href="{{ url_for('static',filename='resource/book.pdf') }}" target="_blank">使用说明</a></li>
              </ul>
            </div>
        </div>
    </nav>
  </header>

  {% block content %}
  {% endblock %}

</div>


<script src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/adminlte.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/parsley.js') }}"></script>

</body>
</html>

app/templates/user/reg.html
{% extends 'user/login_base.html' %}

{% block content %}
<div class="content-wrapper">
    <div class="container">
        <div class="login-box" style="width: 450px;">
            <div class="login-logo">
                <a href="#">注册账号</a>
            </div>
            <div class="login-box-body">
                <p class="login-box-msg"></p>
                <form action="{{ url_for("user.reg") }}" method="post" data-parsley-validate="">
                  <div class="form-group has-feedback">
                    <input name="username" type="text" class="form-control" placeholder="用户名"
                           {% if data %}value="{{ data.username }}" {% endif %}
                           data-parsley-required-message="用户名不能为空" data-parsley-type="alphanum"
                           data-parsley-maxlength="16" required>
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                    {% if message_u %}
                        <p class="help-text">{{ message_u }}</p>
                    {% endif %}
                  </div>
                  <div class="form-group has-feedback">
                    <input name="email" type="email" class="form-control" placeholder="电子邮箱(将作为唯一识别码)"
                           {% if data %}value="{{ data.email }}" {% endif %}
                           data-parsley-required-message="邮箱地址不能为空" data-parsley-type="email"
                           data-parsley-maxlength="64" required>
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                    {% if message_e %}
                        <p class="help-text">{{ message_e }}</p>
                    {% endif %}
                  </div>
                  <div class="form-group has-feedback">
                    <input name="password" type="password" id="password" class="form-control" placeholder="密码"
                           {% if data %}value="{{ data.password }}" {% endif %}
                           data-parsley-type="alphanum" data-parsley-required-message="请设置登录密码" data-parsley-length="[6,32]" required>
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                  </div>
                  <div class="form-group has-feedback">
                    <input name="password2" type="password" class="form-control" placeholder="重复输入密码"
                           {% if data %}value="{{ data.password2 }}" {% endif %}
                           data-parsley-type="alphanum" data-parsley-required-message="请重复登录密码"
                           data-parsley-length="[6,32]" data-parsley-equalto="#password" required>
                    <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
                    {% if message_p %}
                        <p class="help-text">{{ message_p }}</p>
                    {% endif %}
                  </div>
                  <div class="row">
                    <div class="col-xs-8" style="padding-top: 7px;">
                        已经拥有账号？<a href="{{ url_for('user.login') }}" class="text-center">立即登录</a>
                    </div>
                    <div class="col-xs-4">
                        <button type="submit" class="btn btn-success btn-block btn-flat">注册</button>
                    </div>
                  </div>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

app/templates/user/setting_avatar.html
{% extends 'base.html' %}

{% block header_ext %}
    <script src="{{ url_for('static', filename='js/show_invalid_info.js') }}"></script>
{% endblock %}

{% block content %}
    <section class="content-header">
      <h1>
        个人设置
        <small>完善您的个人信息以通过认证</small>
      </h1>
      <ol class="breadcrumb">
        <li style="font-size: 18px;"><a href="{{ url_for('main.index') }}"><i class="fa fa-tags"></i>主页</a></li>
        <li class="active" style="font-size: 18px;">个人设置</li>
      </ol>
    </section>

    <section class="content container-fluid container">
        <div class="row" style="margin-top: 10px;">
            <div class="col-xs-2">
                <div class="box box-primary">
                    <div class="box-header with-border">
                      <h3 class="box-title">设置菜单</h3>

                      <div class="box-tools">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                        </button>
                      </div>
                    </div>
                    <div class="box-body no-padding">
                      <ul class="nav nav-pills nav-stacked">
                        <li><a href="{{ url_for('user.setting_information') }}"><i class="fa fa-inbox"></i> 基本信息设置</a></li>
                        <li><a href="{{ url_for('user.setting_password') }}"><i class="glyphicon glyphicon-lock"></i> 修改用户密码</a></li>
                        <li class="active"><a href="#"><i class="glyphicon glyphicon-picture"></i> 上传用户头像</a></li>
                      </ul>
                    </div>
                </div>
            </div>

            <div class="col-xs-9">
                <div class="box box-primary">
                    <div class="box-header with-border">
                      <h3 class="box-title">上传头像</h3>
                    </div>

                        <form class="form-horizontal" action="{{ url_for('user.setting_avatar') }}" method="post"
                              enctype="multipart/form-data" data-parsley-validate="">
                            <div class="box-body">
                                <div class="form-group clearfix">
                                    <div class="col-md-offset-2 col-md-8 controls">
                                        <img id="user-avatar" src="{{ current_user.avatar_url }}" style="height: 128px;width: 128px;">
                                    </div>
                                </div>
                                <div class="form-group clearfix">
                                    <div class="col-md-offset-2 col-md-8 controls">
                                        <input id="user-avatar-field" class="pic-upload" name="file" accept="image/bmp,image/jpeg,image/png" type="file"
                                               data-parsley-max-file-size="1024" data-parsley-required-message="请选择要上传的图片" required="required">
                                        <p class="help-block">你可以上传 jpg, bmp, png 格式的图片，不超过1M</p>
                                    </div>
                                </div>
                            </div>

                            <div class="box-footer">
                                <button type="submit" class="btn btn-info pull-right">保存</button>
                            </div>

                        </form>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block footer_ext %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('#user-avatar-field').change("#user-avatar", preview_picture);
        });
    </script>
{% endblock %}

app/templates/user/setting_information.html
{% extends 'base.html' %}

{% block header_ext %}
{% endblock %}

{% block content %}
    <section class="content-header">
      <h1>
        个人设置
        <small>完善您的个人信息以通过认证</small>
      </h1>
      <ol class="breadcrumb">
        <li style="font-size: 18px;"><a href="{{ url_for('main.index') }}"><i class="fa fa-tags"></i>主页</a></li>
        <li class="active" style="font-size: 18px;">个人设置</li>
      </ol>
    </section>

    <section class="content container-fluid container">

        {% if status == 'success' %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i> 修改成功!</h4>
        </div>
        {% endif %}

        <div class="row" style="margin-top: 10px;">
            <div class="col-xs-2">
                <div class="box box-primary">
                    <div class="box-header with-border">
                      <h3 class="box-title">个人设置菜单</h3>

                      <div class="box-tools">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                        </button>
                      </div>
                    </div>
                    <div class="box-body no-padding">
                      <ul class="nav nav-pills nav-stacked">
                        <li class="active"><a href="#"><i class="fa fa-inbox"></i> 基本信息设置</a></li>
                        <li><a href="{{ url_for('user.setting_password') }}"><i class="glyphicon glyphicon-lock"></i> 修改用户密码</a></li>
                        <li><a href="{{ url_for('user.setting_avatar') }}"><i class="glyphicon glyphicon-picture"></i> 上传用户头像</a></li>
                      </ul>
                    </div>
                </div>
            </div>

            <div class="col-xs-9">
                <div class="box box-primary">
                    <div class="box-header with-border">
                      <h3 class="box-title">基本信息</h3>
                    </div>

                    <form class="form-horizontal" action="{{ url_for('user.setting_information') }}" method="post">
                        <div class="box-body">
                            <div class="form-group">
                              <label class="col-sm-2 control-label">电子邮箱</label>
                              <div class="col-sm-10">
                                <input type="email" class="form-control" value="{{ current_user.email }}" disabled>
                              </div>
                            </div>

                            <div class="form-group">
                              <label class="col-sm-2 control-label">用户名</label>
                              <div class="col-sm-10">
                                <input type="text" class="form-control" value="{{ current_user.username }}" disabled>
                              </div>
                            </div>

                            <div class="form-group">
                              <label class="col-sm-2 control-label">手机号码</label>
                              <div class="col-sm-10">
                                <input name="phone" type="text" class="form-control" value="{% if current_user.phone %}{{ current_user.phone }}{% endif %}" placeholder="请输入您的11位手机号码">
                              </div>
                            </div>

                            <div class="form-group">
                              <label class="col-sm-2 control-label">真实姓名</label>
                              <div class="col-sm-10">
                                <input name="real_name" type="text" class="form-control" value="{% if current_user.real_name %}{{ current_user.real_name }}{% endif %}" placeholder="请输入您的真实姓名">
                              </div>
                            </div>

                            <div class="form-group">
                              <label class="col-sm-2 control-label">年级专业与班级</label>
                              <div class="col-sm-10">
                                <input name="address" type="text" class="form-control" value="{% if current_user.address %}{{ current_user.address }}{% endif %}" placeholder="请输入您的所在单位">
                              </div>
                            </div>
                        </div>

                        <div class="box-footer">
                            <button type="submit" class="btn btn-info pull-right">保存</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block footer_ext %}
{% endblock %}

app/templates/user/setting_password.html
{% extends 'base.html' %}

{% block header_ext %}
{% endblock %}

{% block content %}
    <section class="content-header">
      <h1>
        个人设置
        <small>完善您的个人信息以通过认证</small>
      </h1>
      <ol class="breadcrumb">
        <li style="font-size: 18px;"><a href="{{ url_for('main.index') }}"><i class="fa fa-tags"></i>主页</a></li>
        <li class="active" style="font-size: 18px;">个人设置</li>
      </ol>
    </section>

    <section class="content container-fluid container">

        {% if status == 'success' %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i> 修改成功!</h4>
        </div>
        {% elif fail_message %}
        <div class="alert alert-warning alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-warning"></i> 修改失败!</h4>
            {{ fail_message }}
        </div>
        {% endif %}

        <div class="row" style="margin-top: 10px;">
            <div class="col-xs-2">
                <div class="box box-primary">
                    <div class="box-header with-border">
                      <h3 class="box-title">个人设置菜单</h3>

                      <div class="box-tools">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                        </button>
                      </div>
                    </div>
                    <div class="box-body no-padding">
                      <ul class="nav nav-pills nav-stacked">
                        <li><a href="{{ url_for('user.setting_information') }}"><i class="fa fa-inbox"></i> 基本信息设置</a></li>
                        <li class="active"><a href="#"><i class="glyphicon glyphicon-lock"></i> 修改用户密码</a></li>
                        <li><a href="{{ url_for('user.setting_avatar') }}"><i class="glyphicon glyphicon-picture"></i> 上传用户头像</a></li>
                      </ul>
                    </div>
                </div>
            </div>

            <div class="col-xs-9">
                <div class="box box-primary">
                    <div class="box-header with-border">
                      <h3 class="box-title">修改密码</h3>
                    </div>

                    <form action="{{ url_for('user.setting_password') }}" method="post" class="form-horizontal">
                        <div class="box-body">

                            <div class="form-group">
                              <label class="col-sm-2 control-label">初始密码</label>
                              <div class="col-sm-10">
                                <input name="origin_password" type="password" class="form-control" required>
                              </div>
                            </div>

                            <div class="form-group">
                              <label class="col-sm-2 control-label">设置新密码</label>
                              <div class="col-sm-10">
                                <input name="new_password" type="password" class="form-control" required>
                              </div>
                            </div>

                            <div class="form-group">
                              <label class="col-sm-2 control-label">重复新密码</label>
                              <div class="col-sm-10">
                                <input name="new_password2" type="password" class="form-control" required>
                              </div>
                            </div>
                        </div>

                        <div class="box-footer">
                            <button type="submit" class="btn btn-info pull-right">保存</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block footer_ext %}
{% endblock %}